### PR TITLE
Fix insecure rb_raise() usage.

### PR DESCRIPTION
**Pull request by raxoft**
Just a little fix to make localmemcache gem compile on debian machines.

### CODE REVIEW

**Comment by raxoft** [comment]
Erm, don't want to sound pushy, but any chance of merging it upstream? Thanks.

**Comment by sck** [comment]
Helll raxoft, I'd love to but I am not sure how I could release gems these days.  Do you happen to have a pointer?  The last time I've used rubyforge.org but I don't know about gem cutter or whatever is used in ruby right now.  That's basically why I can't just make a new release right now.  Thanks for your contribution!

**Comment by raxoft** [comment]
I know nothing at all about gem making myself, sorry. But it can't be that difficult, I think, considering how many half-finished forks are getting released...

BTW, as you see, I have made couple more changes, as I was considering adding LRU removal support, but in the end I have given up. There are dozen more places like that which could use a bit of cleanup, and unfortunately I don't have time for that right now. Also, the fixed hash size seems to be quite a limitation for my needs, and changing that that would require even more serious rewrite.

Anyway, it would be nice if you could merge whatever you choose from this branch, even if you don't release the gem. If someone desperately needs it, they could at least use bundler to pull it directly from github.

Thanks.

**Comment by sck** [comment]
Yeah, good thinking.  There are quite some bugs but I have not yet had time to fix them.  The allocation strategy is flawed too.  I resorted to static alloc sizes when using localmemcache for my customers (I guess that's what you refer to with LRU).   

I am currently trying to finish a project.   And after that I will see what I can do.

**Comment by raxoft** [comment]
I would need the least recently used entries to be removed when the cache gets full. As it is, it is unusable for me, as I can't estimate how much I will store (actually, I can quite certainly guarantee that it will overflow no matter how big I will make it, withing the memory/disk limits I can afford).

Of course, making the LRU pointer swapping directly in the mmaped area would increase the write IO even when reading only, so I wanted to resolve that by keeping the LRU related stuff in normal memory.

So I started browsing the code to see how difficult it would be, and while it would be doable, I decided to give it a pass for now as I don't have that much time at hand. Sorry.

**Comment by sck** [comment]
The idea is that if you do random_pair() + delete in a certain interval, you actually have what you want.  Statistically there is not much difference.  In production I've just had an extra process that would do like 100 delete per second.  You could also pair it with size().

**Comment by raxoft** [comment]
Hmm, right, I can see that working fine in many scenarios.

Unfortunately, in my case the data range from few kb to several hundred kb and I have no control over that. So to make it work as you describe and also to avoid any fragmentation issues, I would have to keep the cache heavily underpopulated, which kind of misses the point. And I still couldn't be 100% sure it won't run out of memory anyway.

Anyway, thanks for merging the change in.

**Comment by sck** [comment]
Yeah, you are right.  The memory allocation is faulty with varying value sizes so it might just defragment the memory too much and then it becomes slow... I've written a new version of lmc for a customer, there might a new release at some point that works a little better.  But I don't know yet when...

**Pull request merged**
